import { genSummaryMapByCoverageMap } from "canyon-data";
import { type FC, useMemo, useState } from "react";
import { CanyonReport } from "./CanyonReport";
import type { CanyonReportAppProps, FileDataResponse } from "./types";

function npmPackageVersionUrl(packageName: string, packageVersion: string): string {
  return `https://www.npmjs.com/package/${packageName}/v/${encodeURIComponent(packageVersion)}`;
}

export const CanyonReportApp: FC<CanyonReportAppProps> = ({
  files = [],
  instrumentCwd,
  generatedAt,
  name = "All files",
  defaultOnlyChange = true,
  defaultValue = "",
  packageName,
  packageVersion,
  height = "calc(100vh - 16px)",
  showFooter = true,
}) => {
  const [value, setValue] = useState(defaultValue);

  const dataSource = useMemo(() => {
    const cwdPrefix = instrumentCwd ? `${instrumentCwd}/` : "";
    return files.map((item) => ({
      ...item,
      path: cwdPrefix ? item.path.replace(cwdPrefix, "") : item.path,
    }));
  }, [files, instrumentCwd]);

  const summaryDataSource = useMemo(() => {
    const diffData = dataSource
      .filter((item) => item.diff?.additions && item.diff.additions.length > 0)
      .map((item) => ({
        path: item.path,
        additions: item.diff!.additions,
      }));

    const coverageMap = dataSource.reduce(
      (acc, cur) => {
        acc[cur.path] = cur;
        return acc;
      },
      {} as Record<string, (typeof dataSource)[number]>,
    );

    // @ts-expect-error genSummaryMapByCoverageMap 入参与 files 实际结构不完全匹配
    return Object.values(genSummaryMapByCoverageMap(coverageMap, diffData));
  }, [dataSource]);

  function onSelect(val: string): Promise<FileDataResponse> {
    return new Promise((resolve) => {
      setValue(val);
      if (val.includes(".")) {
        const file = dataSource.find((item) => item.path === val);
        if (file) {
          resolve({
            // @ts-expect-error file 同时作为 FileCoverageData 使用
            fileCoverage: file,
            fileContent: file.source,
            fileCodeChange: file.diff || { additions: [], deletions: [] },
          });
        } else {
          resolve({
            // @ts-expect-error 未选中文件时允许空 coverage
            fileCoverage: undefined,
            fileContent: "",
            fileCodeChange: { additions: [], deletions: [] },
          });
        }
      } else {
        resolve({
          // @ts-expect-error 目录节点无 coverage
          fileCoverage: undefined,
          fileContent: "",
          fileCodeChange: { additions: [], deletions: [] },
        });
      }
    });
  }

  return (
    <div
      style={{
        height,
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div style={{ flex: 1, minHeight: 0 }}>
        <CanyonReport
          name={name}
          value={value}
          // @ts-expect-error genSummaryMapByCoverageMap 返回值与 DataSourceItem 不完全匹配
          dataSource={summaryDataSource}
          onSelect={onSelect}
          defaultOnlyChange={defaultOnlyChange}
        />
      </div>
      {showFooter && (
        <div
          style={{
            textAlign: "center",
            fontSize: "12px",
            color: "rgba(0,0,0,0.5)",
          }}
        >
          Code coverage generated by{" "}
          <a
            href="https://github.com/canyon-project/canyon"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "#0074D9", textDecoration: "underline" }}
          >
            canyonjs
          </a>
          {packageName && packageVersion ? (
            <>
              {" "}
              ·{" "}
              <a
                href={npmPackageVersionUrl(packageName, packageVersion)}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "#0074D9", textDecoration: "underline" }}
              >
                {packageName} v{packageVersion}
              </a>
            </>
          ) : null}{" "}
          at {generatedAt || new Date().toISOString()}
        </div>
      )}
    </div>
  );
};

export default CanyonReportApp;
