import { ConfigProvider } from 'antd';
import { useEffect, useState } from 'react';
import CanyonReport from './index.tsx';

// 使用常量获取全局数据，提高可维护性
// @ts-ignore
const dataSource = window.data;
// @ts-ignore
const reportName = window.reportName;
// @ts-ignore
const date = window.date;

// 优化动态加载逻辑，添加错误处理和缓存机制
const dynamicLoadingSource = (val:string):Promise<{
  fileCoverage: any;
  fileContent: string;
  fileCodeChange: {
      additions: number[];
      deletions: number[];
  }[];
}> => {
  return new Promise((resolve) => {
    // 如果不是文件路径，返回空数据
    if (!val.includes('.')) {
      return resolve({
        fileCoverage: {},
        fileContent: '',
        fileCodeChange: [],
      });
    }

    // 动态加载脚本
    const script = document.createElement('script');
    script.src = `dynamic-data/${val}.js`;
    console.log(script.src)

    script.onload = () => {
      const data = {
        fileCoverage: window[val].coverage,
        fileContent: window[val].content,
        fileCodeChange: window[val].codeChange || [],
      };

      resolve(data);
      // 用完清理
      document.body.removeChild(script);
      window[val] = undefined;
    };
    document.body.appendChild(script);
  });
};

function App() {
  const [value, setValue] = useState(window.location.hash.slice(1));
  const [loading, setLoading] = useState(false);

  function onOnlyShowChangedChange() {

  }
  // 使用 useCallback 优化函数引用稳定性
  const onSelect = (val:string):Promise<{
    fileCoverage: any;
    fileContent: string;
    fileCodeChange: {
        additions: number[];
        deletions: number[];
    }[];
  }> => {
    window.location.hash = val;
    setLoading(true);

    return dynamicLoadingSource(val)
      .then((r) => {
        setValue(val);
        return r;
      })
  }

  // 监听 hash 变化
  useEffect(() => {
    const handleHashChange = () => {
      const newValue = window.location.hash.slice(1);
      if (newValue !== value) {
        onSelect(newValue);
      }
    };

    window.addEventListener('hashchange', handleHashChange);
    return () => window.removeEventListener('hashchange', handleHashChange);
  }, [value, onSelect]);
  return (
    <div className={'p-[6px] pb-0'}>
      <div style={{ minHeight: 'calc(100vh - 50px)' }}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#0071c2',
            },
          }}
        >
          <CanyonReport
            name={reportName}
            dataSource={dataSource.reduce((acc:any, cur:any) => {
              acc[cur.path] = cur;
              return acc;
            }, {})}
            onSelect={onSelect}
            value={value}
            onlyShowChangedDisabled={false}
            onOnlyShowChangedChange={onOnlyShowChangedChange}
            onlyShowChanged={false}
          />
        </ConfigProvider>
      </div>
      <footer
        style={{
          color: 'rgba(0,0,0,0.5)',
          fontSize: '12px',
          textAlign: 'center',
          padding: '6px',
        }}
        className={'p-[6px] text-center'}
      >
        Code coverage generated by{' '}
        <a href='https://github.com/canyon-project/canyon/' target='_blank' rel='noreferrer'>
          canyon
        </a>{' '}
        at {date}
      </footer>
    </div>
  );
}
export default App;
