catalogMode: prefer

shellEmulator: true

packages:
  - docs
  - packages/*
  - examples/*

catalog:
  # bundler
  vite: 8.0.0-beta.0

  # typescript experimental
  '@typescript/native-preview': ^7.0.0-dev.20251215.1

  # istanbul core
  istanbul-lib-coverage: ^3.2.2
  istanbul-lib-report: ^3.0.1
  istanbul-lib-source-maps: ^5.0.6
  istanbul-reports: ^3.2.0

  # istanbul types
  '@types/istanbul-lib-coverage': ^2.0.6
  '@types/istanbul-lib-report': ^3.0.3
  '@types/istanbul-lib-source-maps': ^4.0.4
  '@types/istanbul-reports': ^3.0.4

  "@types/node": "^24.10.1"
  "@types/react": "^19.2.5"
  "@types/react-dom": "^19.2.3"
  "globals": "^16.5.0"

  "react": "^19.2.0"
  "react-dom": "^19.2.0"

overrides:
  vite: 8.0.0-beta.0
  '@typescript/native-preview': 7.0.0-dev.20251215.1
