export const coverageObj = {
    // id: require('cuid')(), // 假设这里有类似cuid的函数来生成唯一ID，需根据实际情况引入相应库
    branch: "-",
    compareTarget: "",
    provider: "",
    buildProvider: "",
    buildID: "",
    projectID: "",
    sha: "",
    reporter: "",
    reportID: "",
    covType: "all",
    statementsTotal: 0,
    statementsCovered: 0,
    branchesTotal: 0,
    branchesCovered: 0,
    functionsTotal: 0,
    functionsCovered: 0,
    linesTotal: 0,
    linesCovered: 0,
    newlinesTotal: 0,
    newlinesCovered: 0,
    summary: Buffer.from([]),
    hit: Buffer.from([]),
    // instrumentCwd: "",
    // createdAt: new Date(),
    // updatedAt: new Date(),
};
