export const coverageObj = {
  // id: require('cuid')(), // 假设这里有类似cuid的函数来生成唯一ID，需根据实际情况引入相应库
  branch: "-",
  compareTarget: "",
  provider: "",
  buildProvider: "",
  buildID: "",
  projectID: "",
  sha: "",
  reporter: "",
  reportID: "",
  covType: "",
  statementsTotal: 0,
  statementsCovered: 0,
  summary: "",
  hit: "",
  map: "",
  instrumentCwd: "",
  // createdAt: new Date(),
  // updatedAt: new Date(),
};
