import { useState } from 'react';
import { ConfigProvider } from 'antd';
import CanyonReport from './index.tsx';
const dataSource = window.data;
const reportName = window.reportName;
const date = window.date;
const dynamicLoadingSource = (val) => {
  return new Promise((resolve) => {
    if (!val.includes('.')) {
      resolve({
        fileCoverage: undefined,
        fileContent: undefined,
        fileCodeChange: [],
      });
    } else {
      const script = document.createElement('script');
      script.src = 'dynamic-data/' + val + '.js';
      script.onload = () => {
        resolve({
          fileCoverage: window[val].coverage,
          fileContent: window[val].content,
          fileCodeChange: [],
        });
        document.body.removeChild(script);
        window[val] = undefined;
      };
      document.body.appendChild(script);
    }
  });
};

function App() {
  const [value, setValue] = useState(window.location.hash.slice(1));
  const onSelect = (val) => {
    window.location.hash = val;
    return dynamicLoadingSource(val).then((r) => {
      setValue(val);
      return r;
    });
  };
  return (
    <div className={'p-[10px] pb-0'}>
      <div style={{ minHeight: 'calc(100vh - 50px)' }}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#0071c2',
            },
            // algorithm: isDark ? [darkAlgorithm] : [],
          }}
        >
          <CanyonReport
            name={reportName}
            dataSource={dataSource.reduce((acc, cur) => {
              acc[cur.path] = cur;
              return acc;
            }, {})}
            onSelect={onSelect}
            value={value}
          />
        </ConfigProvider>
      </div>
      <footer
        style={{
          color: 'rgba(0,0,0,0.5)',
          fontSize: '12px',
          textAlign: 'center',
          padding: '10px',
        }}
        className={'text-center p-[10px]'}
      >
        Code coverage generated by{' '}
        <a
          href="https://github.com/canyon-project/canyon/"
          target="_blank"
          rel="noreferrer"
        >
          canyon
        </a>{' '}
        at {date}
      </footer>
    </div>
  );
}
export default App;
