[package]
name = "canyon-core"
version = "0.1.1-beta.2"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen='0.2.95'
