-- Create coverage table
CREATE TABLE IF NOT EXISTS coverage (
    id VARCHAR PRIMARY KEY,
    sha VARCHAR NOT NULL,
    branch VARCHAR NOT NULL,
    compare_target VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    build_provider VARCHAR NOT NULL,
    build_id VARCHAR NOT NULL,
    project_id VARCHAR NOT NULL,
    reporter VARCHAR NOT NULL,
    report_id VARCHAR NOT NULL,
    cov_type VARCHAR NOT NULL,
    branches_total INTEGER NOT NULL,
    branches_covered INTEGER NOT NULL,
    functions_total INTEGER NOT NULL,
    functions_covered INTEGER NOT NULL,
    lines_total INTEGER NOT NULL,
    lines_covered INTEGER NOT NULL,
    statements_total INTEGER NOT NULL,
    statements_covered INTEGER NOT NULL,
    newlines_total INTEGER NOT NULL,
    newlines_covered INTEGER NOT NULL,
    changebranches_covered INTEGER NOT NULL,
    changebranches_total INTEGER NOT NULL,
    changefunctions_covered INTEGER NOT NULL,
    changefunctions_total INTEGER NOT NULL,
    summary BYTEA,
    hit BYTEA,
    created_at TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
