// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/coverage/map": {
            "get": {
                "description": "获取详细的覆盖率映射数据，包含语句、函数、分支等详细的覆盖率信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "获取覆盖率映射",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交SHA",
                        "name": "sha",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "构建提供商",
                        "name": "buildProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "构建ID",
                        "name": "buildID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提供商",
                        "name": "reportProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "覆盖率映射数据",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/coverage/overview/commits": {
            "get": {
                "description": "根据仓库ID和SHA获取指定commit的覆盖率概览信息，包括总体覆盖率统计和构建组信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "获取一个commit的覆盖率概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交SHA",
                        "name": "sha",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "构建提供商",
                        "name": "buildProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "构建ID",
                        "name": "buildID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提供商",
                        "name": "reportProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "覆盖率概览信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/coverage/overview/pulls": {
            "get": {
                "description": "根据仓库ID和PR号获取指定pull request的覆盖率概览信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "获取一个pull request的覆盖率概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PR号",
                        "name": "pullNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "构建提供商",
                        "name": "buildProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "构建ID",
                        "name": "buildID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提供商",
                        "name": "reportProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PR覆盖率概览信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/coverage/overview/multiple-commits": {
            "get": {
                "description": "根据仓库ID和多个SHA获取指定commits的覆盖率概览信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "获取多个commits的覆盖率概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交SHA列表，用逗号分隔",
                        "name": "shas",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "构建提供商",
                        "name": "buildProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "构建ID",
                        "name": "buildID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提供商",
                        "name": "reportProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "多commits覆盖率概览信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/coverage/summary/map": {
            "get": {
                "description": "获取覆盖率数据的摘要映射，包含文件级别的覆盖率统计信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "获取覆盖率摘要映射",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交SHA",
                        "name": "sha",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "构建提供商",
                        "name": "buildProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "构建ID",
                        "name": "buildID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提供商",
                        "name": "reportProvider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "覆盖率摘要映射",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/repo": {
            "get": {
                "description": "根据关键词搜索仓库列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repository"
                ],
                "summary": "获取仓库列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "仓库列表",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/repo/{repoID}": {
            "get": {
                "description": "根据仓库ID获取详细的仓库信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repository"
                ],
                "summary": "根据仓库ID获取仓库信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "仓库详细信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/repo/{repoID}/commits": {
            "get": {
                "description": "获取指定仓库的提交记录列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repository"
                ],
                "summary": "获取仓库提交记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "仓库ID",
                        "name": "repoID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "提交记录列表",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/vi/health": {
            "get": {
                "description": "检查服务健康状态，包括数据库连接状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务健康状态",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "503": {
                        "description": "服务不可用",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CoverageQueryDto": {
            "type": "object",
            "properties": {
                "buildID": {
                    "description": "构建ID",
                    "type": "string",
                    "example": "build-123"
                },
                "buildProvider": {
                    "description": "构建提供商",
                    "type": "string",
                    "example": "jenkins"
                },
                "filePath": {
                    "description": "文件路径",
                    "type": "string",
                    "example": "src/main.go"
                },
                "provider": {
                    "description": "提供商名称",
                    "type": "string",
                    "example": "github"
                },
                "reportID": {
                    "description": "报告ID",
                    "type": "string",
                    "example": "report-456"
                },
                "reportProvider": {
                    "description": "报告提供商",
                    "type": "string",
                    "example": "jest"
                },
                "repoID": {
                    "description": "仓库ID",
                    "type": "string",
                    "example": "owner/repo"
                },
                "sha": {
                    "description": "提交SHA",
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "dto.CoverageSummaryQueryDto": {
            "type": "object",
            "properties": {
                "buildID": {
                    "description": "构建ID",
                    "type": "string",
                    "example": "build-123"
                },
                "buildProvider": {
                    "description": "构建提供商",
                    "type": "string",
                    "example": "jenkins"
                },
                "filePath": {
                    "description": "文件路径",
                    "type": "string",
                    "example": "src/main.go"
                },
                "provider": {
                    "description": "提供商名称",
                    "type": "string",
                    "example": "github"
                },
                "reportID": {
                    "description": "报告ID",
                    "type": "string",
                    "example": "report-456"
                },
                "reportProvider": {
                    "description": "报告提供商",
                    "type": "string",
                    "example": "jest"
                },
                "repoID": {
                    "description": "仓库ID",
                    "type": "string",
                    "example": "owner/repo"
                },
                "sha": {
                    "description": "提交SHA",
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "dto.RepoQueryDto": {
            "type": "object",
            "properties": {
                "keyword": {
                    "description": "搜索关键词",
                    "type": "string",
                    "example": "react"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Canyon Backend API",
	Description:      "Canyon 代码覆盖率管理平台后端 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
