export type {
  BranchCoverageByLine,
  BranchHitMap,
  BranchLineCoverage,
  BranchMap,
  BranchMapping,
  BranchType,
  CanyonCoverageHitPayload,
  CanyonCoverageMapInitPayload,
  CanyonFileCoverageHit,
  CanyonFileCoverageMap,
  CoverageIndex,
  CoverageMapData,
  CoverageSummaryData,
  CoverageTotals,
  FileCoverageData,
  FileCoverageHitData,
  FileCoverageMapData,
  FunctionMap,
  FunctionMapping,
  HitMap,
  InputSourceMap,
  LineHitMap,
  Location,
  Range,
  StatementMap,
} from './coverage.js';
