name: Build Uploader

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
  release:
    types: [created, published]

jobs:
  build-multi:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: linux-binary
            exe_suffix: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: macos-binary
            exe_suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-binary
            exe_suffix: ".exe"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src, rustc-dev, llvm-tools-preview

      - name: Install MUSL tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build -p uploader --target ${{ matrix.target }} --release

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/uploader${{ matrix.exe_suffix }}