name: e2e tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
#        切换pnpm下的playwright目录
      - name: Change directory
        run: cd packages/canyon-e2e
      - name: Install Playwright Browsers
        run: cd packages/canyon-e2e && ls && pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - name: Upload coverage reports to Canyon
        run: |
          curl -LOs https://github.com/canyon-project/uploader/releases/download/v0.0.1/uploader
          chmod +x uploader
          ./uploader
