name: Npm Publish swc-plugin-canyon

on:
  push:
    branches:
      - main

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # 新增条件：仅当提交信息匹配指定格式时触发
    if: |
      contains(github.event.head_commit.message, ': (swc-plugin-canyon): ') &&
      (github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: |
          corepack enable
          pnpm i

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm --filter=swc-plugin-canyon publish -f --no-git-checks --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}