name: Publish babel-plugin-canyon

on:
  push:
    branches: [ "*" ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # 新增条件：仅当提交信息匹配指定格式时触发
    if: |
      contains(github.event.head_commit.message, ': (babel-plugin-canyon): ') &&
      (github.ref == 'refs/heads/main')
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm --filter=babel-plugin-canyon publish -f --no-git-checks --access=public || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - run: |
          pnpm dist-tag add babel-plugin-canyon@2.0.6 latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
