name: rsbuild-plugin-istanbul Release

on:
  push:
    branches: [ "*" ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # 新增条件：仅当提交信息匹配指定格式时触发
    if: |
      contains(github.event.head_commit.message, '(rsbuild-plugin-istanbul):') &&
      (github.ref == 'refs/heads/main')
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd istanbul/rsbuild-plugin-istanbul && pnpm install
      - run: cd istanbul/rsbuild-plugin-istanbul && pnpm --filter=rsbuild-plugin-istanbul publish -f --no-git-checks --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
