name: Test Application Startup on CentOS 7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-startup:
    runs-on: ubuntu-latest  # 使用 CentOS 7 环境

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 使用你项目所需的 Node.js 版本
          cache: 'pnpm'       # 启用 pnpm 缓存

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test application startup
        run: |
          # 启动应用并在后台运行
          node packages/canyon-backend/dist/main.js &

          # 获取进程ID
          APP_PID=$!

          # 等待几秒让应用启动
          sleep 10

          # 检查应用是否仍在运行
          if ps -p $APP_PID > /dev/null; then
            echo "Application started successfully"
            # 关闭应用
            kill $APP_PID
            exit 0
          else
            echo "Application failed to start"
            exit 1
          fi
