name: Build and Deploy Vite Project

on:
  push:
    branches:
      - dev  # 监听主分支的推送事件

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i -g pnpm && npm i -g canyon-uploader && pnpm install
      - name: Build
        run: pnpm run build:report
      - name: Upload coverage map
        run: cd packages/canyon-report && canyon-uploader map --dsn=https://collect.canyonjs.org/coverage/map/client
      - name: Install Playwright Browsers
        run: cd packages/canyon-report && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd packages/canyon-report && npx playwright test && canyon-uploader hit --dsn=https://collect.canyonjs.org/coverage/client
